# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 44) do

  create_table "avatars", :force => true do |t|
    t.column "parent_id",       :integer
    t.column "content_type",    :string
    t.column "filename",        :string
    t.column "thumbnail",       :string
    t.column "size",            :integer
    t.column "width",           :integer
    t.column "height",          :integer
    t.column "user_id",         :integer
    t.column "current_user_id", :integer
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "categories", :force => true do |t|
    t.column "name",     :string
    t.column "position", :integer, :default => 0
  end

  create_table "events", :force => true do |t|
    t.column "title",       :string
    t.column "description", :text
    t.column "date",        :datetime
    t.column "private",     :boolean,  :default => false
    t.column "reminder",    :boolean
    t.column "user_id",     :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  add_index "events", ["date"], :name => "index_events_on_date"

  create_table "forums", :force => true do |t|
    t.column "category_id",  :integer
    t.column "name",         :string
    t.column "description",  :text
    t.column "topics_count", :integer,  :default => 0
    t.column "posts_count",  :integer,  :default => 0
    t.column "position",     :integer,  :default => 0
    t.column "last_post_id", :integer
    t.column "last_post_at", :datetime
    t.column "last_post_by", :integer
  end

  add_index "forums", ["category_id"], :name => "index_forums_on_category_id"
  add_index "forums", ["category_id", "last_post_at"], :name => "index_forums_on_last_post_at"

  create_table "headers", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "description",  :text
    t.column "user_id",      :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "votes",        :integer,  :default => 0
  end

  create_table "options", :force => true do |t|
    t.column "site_title",      :string
    t.column "site_tagline",    :string
    t.column "footer_left",     :text
    t.column "footer_right",    :text
    t.column "invitation_only", :boolean, :default => false
    t.column "private_site",    :boolean, :default => false
    t.column "admin_rank",      :string
    t.column "avatars_path",    :string
    t.column "login_image",     :string
    t.column "announcement",    :text
    t.column "advertisement",   :text
    t.column "newest_user",     :string
    t.column "theme_id",        :integer
  end

  create_table "posts", :force => true do |t|
    t.column "user_id",    :integer
    t.column "topic_id",   :integer
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "updated_by", :integer
  end

  add_index "posts", ["topic_id"], :name => "index_posts_on_topic_id"
  add_index "posts", ["user_id", "created_at"], :name => "index_posts_on_user_id"

  create_table "pun_bans", :force => true do |t|
    t.column "username", :string,  :limit => 200
    t.column "ip",       :string
    t.column "email",    :string,  :limit => 50
    t.column "message",  :string
    t.column "expire",   :integer, :limit => 10
  end

  create_table "pun_categories", :force => true do |t|
    t.column "cat_name",      :string,  :limit => 80, :default => "New Category", :null => false
    t.column "disp_position", :integer, :limit => 10, :default => 0,              :null => false
  end

  create_table "pun_forums", :force => true do |t|
    t.column "forum_name",    :string,  :limit => 80,  :default => "New forum", :null => false
    t.column "forum_desc",    :text
    t.column "redirect_url",  :string,  :limit => 100
    t.column "moderators",    :text
    t.column "num_topics",    :integer, :limit => 8,   :default => 0,           :null => false
    t.column "num_posts",     :integer, :limit => 8,   :default => 0,           :null => false
    t.column "last_post",     :integer, :limit => 10
    t.column "last_post_id",  :integer, :limit => 10
    t.column "last_poster",   :string,  :limit => 200
    t.column "sort_by",       :boolean,                :default => false,       :null => false
    t.column "disp_position", :integer, :limit => 10,  :default => 0,           :null => false
    t.column "cat_id",        :integer, :limit => 10,  :default => 0,           :null => false
  end

  create_table "pun_posts", :force => true do |t|
    t.column "poster",       :string,  :limit => 200, :default => "",    :null => false
    t.column "poster_id",    :integer, :limit => 10,  :default => 1,     :null => false
    t.column "poster_ip",    :string,  :limit => 15
    t.column "poster_email", :string,  :limit => 50
    t.column "message",      :text,                   :default => "",    :null => false
    t.column "hide_smilies", :boolean,                :default => false, :null => false
    t.column "posted",       :integer, :limit => 10,  :default => 0,     :null => false
    t.column "edited",       :integer, :limit => 10
    t.column "edited_by",    :string,  :limit => 200
    t.column "topic_id",     :integer, :limit => 10,  :default => 0,     :null => false
  end

  add_index "pun_posts", ["topic_id"], :name => "posts_topic_id_idx"
  add_index "pun_posts", ["poster_id", "topic_id"], :name => "posts_multi_idx"

  create_table "pun_ranks", :force => true do |t|
    t.column "rank",      :string,  :limit => 50, :default => "", :null => false
    t.column "min_posts", :integer, :limit => 8,  :default => 0,  :null => false
  end

  create_table "pun_topics", :force => true do |t|
    t.column "poster",       :string,  :limit => 200, :default => "",    :null => false
    t.column "subject",      :string,                 :default => "",    :null => false
    t.column "posted",       :integer, :limit => 10,  :default => 0,     :null => false
    t.column "last_post",    :integer, :limit => 10,  :default => 0,     :null => false
    t.column "last_post_id", :integer, :limit => 10,  :default => 0,     :null => false
    t.column "last_poster",  :string,  :limit => 200
    t.column "num_views",    :integer, :limit => 8,   :default => 0,     :null => false
    t.column "num_replies",  :integer, :limit => 8,   :default => 0,     :null => false
    t.column "closed",       :boolean,                :default => false, :null => false
    t.column "sticky",       :boolean,                :default => false, :null => false
    t.column "moved_to",     :integer, :limit => 10
    t.column "forum_id",     :integer, :limit => 10,  :default => 0,     :null => false
  end

  add_index "pun_topics", ["forum_id"], :name => "topics_forum_id_idx"
  add_index "pun_topics", ["moved_to"], :name => "topics_moved_to_idx"

  create_table "pun_users", :force => true do |t|
    t.column "group_id",         :integer, :limit => 10,  :default => 4,         :null => false
    t.column "username",         :string,  :limit => 200, :default => "",        :null => false
    t.column "password",         :string,  :limit => 40,  :default => "",        :null => false
    t.column "email",            :string,  :limit => 50,  :default => "",        :null => false
    t.column "title",            :string,  :limit => 50
    t.column "realname",         :string,  :limit => 40
    t.column "url",              :string,  :limit => 100
    t.column "jabber",           :string,  :limit => 75
    t.column "icq",              :string,  :limit => 12
    t.column "msn",              :string,  :limit => 50
    t.column "aim",              :string,  :limit => 30
    t.column "yahoo",            :string,  :limit => 30
    t.column "location",         :string,  :limit => 30
    t.column "use_avatar",       :boolean,                :default => false,     :null => false
    t.column "signature",        :text
    t.column "disp_topics",      :integer, :limit => 3
    t.column "disp_posts",       :integer, :limit => 3
    t.column "email_setting",    :boolean,                :default => true,      :null => false
    t.column "save_pass",        :boolean,                :default => true,      :null => false
    t.column "notify_with_post", :boolean,                :default => false,     :null => false
    t.column "show_smilies",     :boolean,                :default => true,      :null => false
    t.column "show_img",         :boolean,                :default => true,      :null => false
    t.column "show_img_sig",     :boolean,                :default => true,      :null => false
    t.column "show_avatars",     :boolean,                :default => true,      :null => false
    t.column "show_sig",         :boolean,                :default => true,      :null => false
    t.column "timezone",         :float,                  :default => 0.0,       :null => false
    t.column "language",         :string,  :limit => 25,  :default => "English", :null => false
    t.column "style",            :string,  :limit => 25,  :default => "Oxygen",  :null => false
    t.column "num_posts",        :integer, :limit => 10,  :default => 0,         :null => false
    t.column "last_post",        :integer, :limit => 10
    t.column "registered",       :integer, :limit => 10,  :default => 0,         :null => false
    t.column "registration_ip",  :string,  :limit => 15,  :default => "0.0.0.0", :null => false
    t.column "last_visit",       :integer, :limit => 10,  :default => 0,         :null => false
    t.column "admin_note",       :string,  :limit => 30
    t.column "activate_string",  :string,  :limit => 50
    t.column "activate_key",     :string,  :limit => 8
    t.column "birthday",         :string,  :limit => 10,  :default => "0-0-0",   :null => false
  end

  add_index "pun_users", ["registered"], :name => "users_registered_idx"
  add_index "pun_users", ["username"], :name => "users_username_idx"

  create_table "ranks", :force => true do |t|
    t.column "title",     :string
    t.column "min_posts", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "themes", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "user_id",      :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "topics", :force => true do |t|
    t.column "user_id",      :integer
    t.column "title",        :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "views",        :integer,  :default => 0
    t.column "posts_count",  :integer,  :default => 0
    t.column "last_post_id", :integer
    t.column "last_post_at", :datetime
    t.column "last_post_by", :integer
    t.column "private",      :boolean,  :default => false
    t.column "closed",       :boolean,  :default => false
    t.column "sticky",       :boolean,  :default => false
    t.column "forum_id",     :integer
  end

  add_index "topics", ["forum_id"], :name => "index_topics_on_forum_id"
  add_index "topics", ["forum_id", "last_post_at"], :name => "index_topics_on_last_post_at"

  create_table "uploads", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "user_id",      :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",              :string
    t.column "email",              :string
    t.column "password_hash",      :string
    t.column "created_at",         :datetime
    t.column "last_login_at",      :datetime
    t.column "admin",              :boolean,  :default => false
    t.column "posts_count",        :integer,  :default => 0
    t.column "signature",          :string
    t.column "bio",                :text
    t.column "profile_updated_at", :datetime
    t.column "online_at",          :datetime
    t.column "banned_until",       :datetime
    t.column "ban_message",        :string
    t.column "avatar_id",          :integer
    t.column "theme_id",           :integer
  end

  add_index "users", ["online_at"], :name => "index_users_on_online_at"

end
